name: Nodejs Chart CI Pipeline

trigger:
  branches:
    include:
      - refs/tags/*

pr:
  branches:
    include:
      - master

variables:
  azureSubscriptionEndpoint: DCD-CFT-Sandbox
  azureContainerRegistry: hmcstsandbox.azurecr.io

jobs:
  - job: Build
    pool:
      vmImage: Ubuntu 16.04
    steps:
      - task: Docker@1
        displayName: Build image
        inputs:
          command: build
          azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
          azureContainerRegistry: $(azureContainerRegistry)
          dockerFile: Dockerfile
          imageName: $(Build.Repository.Name)
