name: Nodejs base images pipeline

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

pr:
  - master

variables:
  azureContainerRegistry: hmctspublic.azurecr.io
  azureSubscriptionEndpoint: azurerm-prod
  vmImage: Ubuntu-18.04

jobs:
  - job: Build
    strategy:
      matrix:
        alpine-node-12:
          imageDockerfilePath: 12/alpine/Dockerfile
          imageName: base/node
          tag: 12-alpine
        buster-slim-node-12:
          imageDockerfilePath: 12/buster-slim/Dockerfile
          imageName: base/node
          tag: 12-buster-slim
        alpine-node-14:
          imageDockerfilePath: 14/alpine/Dockerfile
          imageName: base/node
          tag: 14-alpine
        buster-slim-node-14:
          imageDockerfilePath: 14/buster-slim/Dockerfile
          imageName: base/node
          tag: 14-buster-slim
    pool:
      vmImage: $(vmImage)
    steps:
      - template: steps/build.yml
        parameters:
          imageDockerfilePath: $(imageDockerfilePath)
          imageName: $(imageName)
          tag: $(tag)
          azureContainerRegistry: $(azureContainerRegistry)
          azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)

  - job: Release
    dependsOn: Build
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master')) # Master branch only
    strategy:
      matrix:
        alpine-node-12:
          imageName: base/node
          tag: 12-alpine
        buster-slim-node-12:
          imageName: base/node
          tag: 12-buster-slim
        alpine-node-14:
          imageName: base/node
          tag: 12-alpine
        buster-slim-node-14:
          imageName: base/node
          tag: 12-buster-slim
    pool:
      vmImage: $(vmImage)
    steps:
      - template: steps/release.yml
        parameters:
          imageName: $(imageName)
          tag: $(tag)
          azureContainerRegistry: $(azureContainerRegistry)
          azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
