name: Nodejs base images pipeline

trigger:
  batch: true
  paths:
    exclude:
      - README.md

pr:
  - master

variables:
  alpineImageName: hmcts/base/node/alpine-lts-10

jobs:
  - job: Build
    pool:
      vmImage: "Ubuntu-16.04"
    steps:
      - template: steps/login-build-tag.yml
        parameters:
          azureSubscriptionEndpoint: azurerm-sandbox
          azureContainerRegistry: hmctssandbox.azurecr.io
          imageDockerfilePath: 10/alpine/Dockerfile
          imageName: $(alpineImageName)

  - job: Sandbox_Release
    dependsOn: Build
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master')) # Master branch only
    pool:
      vmImage: Ubuntu 16.04
    steps:
      - task: Docker@1
        displayName: Push image
        inputs:
          command: push
          azureSubscriptionEndpoint: azurerm-sandbox
          azureContainerRegistry: hmctssandbox.azurecr.io
          imageName: $(alpineImageName):latest
