name: Nodejs base images pipeline

trigger:
  batch: true
  paths:
    exclude:
      - README.md

pr:
  - master

jobs:
  - job: Build
    pool:
      vmImage: "Ubuntu-16.04"
    steps:
      - template: steps/build.yml
        parameters:
          azureSubscriptionEndpoint: azurerm-sandbox
          azureContainerRegistry: hmctssandbox.azurecr.io
          imageDockerfilePath: 10/alpine/Dockerfile
          imageName: hmcts/base/node/alpine-lts-10

  - job: SandboxRelease
    displayName: Sandbox Release
    dependsOn: Build
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master')) # Master branch only
    pool:
      vmImage: Ubuntu 16.04
    steps:
      - template: steps/release.yml
        parameters:
          azureSubscriptionEndpoint: azurerm-sandbox
          azureContainerRegistry: hmctssandbox.azurecr.io
          imageDockerfilePath: 10/alpine/Dockerfile
          imageName: hmcts/base/node/alpine-lts-10
