name: Nodejs base images pipeline

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
      - README.md

pr:
  - master

jobs:
  - job: buildAlpine
    pool:
      vmImage: "Ubuntu-16.04"
    steps:
      - template: steps/build.yml
        parameters:
          azureSubscriptionEndpoint: azurerm-sandbox
          azureContainerRegistry: hmctssandbox.azurecr.io
          imageDockerfilePath: 10/alpine/Dockerfile
          imageName: hmcts/base/node/alpine-lts-10

  - job: sandboxReleaseAlpine
    displayName: Sandbox Release
    dependsOn: buildAlpine
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master')) # Master branch only
    pool:
      vmImage: Ubuntu 16.04
    steps:
      - template: steps/release.yml
        parameters:
          azureSubscriptionEndpoint: azurerm-sandbox
          azureContainerRegistry: hmctssandbox.azurecr.io
          imageDockerfilePath: 10/alpine/Dockerfile
          imageName: hmcts/base/node/alpine-lts-10

  - job: buildDebian
    pool:
      vmImage: "Ubuntu-16.04"
    steps:
      - template: steps/build.yml
        parameters:
          azureSubscriptionEndpoint: azurerm-sandbox
          azureContainerRegistry: hmctssandbox.azurecr.io
          imageDockerfilePath: 10/stretch-slim/Dockerfile
          imageName: hmcts/base/node/stretch-slim-lts-10

  - job: sandboxReleaseDebian
    displayName: Sandbox Release Debian
    dependsOn: buildDebian
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master')) # Master branch only
    pool:
      vmImage: Ubuntu 16.04
    steps:
      - template: steps/release.yml
        parameters:
          azureSubscriptionEndpoint: azurerm-sandbox
          azureContainerRegistry: hmctssandbox.azurecr.io
          imageDockerfilePath: 10/stretch-slim/Dockerfile
          imageName: hmcts/base/node/stretch-slim-lts-10
