name: Nodejs base images pipeline

trigger:
  branches:
    include:
      - refs/tags/*

pr:
  branches:
    include:
      - master

pool:
  vmImage: "Ubuntu-16.04"

# variables:
#   azureSubscriptionEndpoint: azurerm-sandbox
#   azureContainerRegistry: hmctssandbox.azurecr.io
#   imageName: hmcts/base/node/alpine-lts-10
#   imageDockerfilePath: 10/alpine/Dockerfile

steps:
  - template: steps/login-build-tag.yml
    parameters:
      azureSubscriptionEndpoint: azurerm-sandbox
      azureContainerRegistry: hmctssandbox.azurecr.io
      imageDockerfilePath: 10/alpine/Dockerfile
      imageName: hmcts/base/node/alpine-lts-10
  # - task: Docker@1
  #   displayName: Push image
  #   inputs:
  #     command: push
  #     azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
  #     azureContainerRegistry: $(azureContainerRegistry)
  #     imageName: $(imageName):latest
