name: Nodejs base images pipeline

trigger:
  branches:
    include:
      - refs/tags/*

pr:
  branches:
    include:
      - master

pool:
  vmImage: "Ubuntu-16.04"

variables:
  azureSubscriptionEndpoint: azurerm-sandbox
  azureContainerRegistry: hmctssandbox.azurecr.io
  imageName: hmcts/base/node/alpine-lts-10

steps:
  - task: Docker@1
    displayName: Container registry login
    inputs:
      azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureContainerRegistry: $(azureContainerRegistry)
      command: login
  - task: Docker@1
    displayName: Build image
    inputs:
      command: build
      azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureContainerRegistry: $(azureContainerRegistry)
      dockerFile: ./10/alpine/Dockerfile
      imageName: $(azureContainerRegistry)/$(imageName):latest
  - task: Docker@1
    displayName: Tag image
    inputs:
      command: tag
      azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureContainerRegistry: $(azureContainerRegistry)
      imageName: $(azureContainerRegistry)/$(imageName):latest
      arguments: $(azureContainerRegistry)/$(imageName):$(Build.BuildId)
  - task: Docker@1
    displayName: Push image
    inputs:
      command: push
      azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureContainerRegistry: $(azureContainerRegistry)
      imageName: $(azureContainerRegistry)/$(imageName):latest
  # - script: docker build -t $(azureContainerRegistry)/$(imageName) ./10/alpine/
