steps:
  - task: Docker@1
    displayName: Container registry login
    inputs:
      azureContainerRegistry: ${{ parameters.azureContainerRegistry }}
      azureSubscriptionEndpoint: ${{ parameters.azureSubscriptionEndpoint }}
      command: login

  - task: CmdLine@2
    displayName: Lint Dockerfile
    inputs:
      failOnStderr: true
      script: |
        sudo npm install -g dockerlint
        dockerlint ${{ parameters.imageDockerfilePath }}

  - task: Docker@1
    displayName: Build image
    inputs:
      command: Build
      azureContainerRegistry: ${{ parameters.azureContainerRegistry }}
      azureSubscriptionEndpoint: ${{ parameters.azureSubscriptionEndpoint }}
      dockerFile: ${{ parameters.imageDockerfilePath }}
      imageName: ${{ parameters.azureContainerRegistry }}/${{ parameters.imageName }}:${{ parameters.tag }}-$(Build.SourceVersion)

  - task: CmdLine@2
    displayName: Test image
    inputs:
      failOnStderr: true
      script: ./test-build.sh ${{ parameters.azureContainerRegistry }}/${{ parameters.imageName }} ${{ parameters.tag }}-$(Build.SourceVersion)

  - task: Docker@1
    displayName: Push image
    inputs:
      command: push
      azureSubscriptionEndpoint: ${{ parameters.azureSubscriptionEndpoint }}
      azureContainerRegistry: ${{ parameters.azureContainerRegistry }}
      imageName: ${{ parameters.azureContainerRegistry }}/${{parameters.imageName}}:${{ parameters.tag }}-$(Build.SourceVersion)
