steps:
  - task: Docker@1
    displayName: Container registry login
    inputs:
      azureSubscriptionEndpoint: ${{ parameters.azureSubscriptionEndpoint }}
      azureContainerRegistry: ${{ parameters.azureContainerRegistry }}
      command: login

  - task: Docker@1
    displayName: Build image
    inputs:
      command: build
      azureSubscriptionEndpoint: ${{ parameters.azureSubscriptionEndpoint }}
      azureContainerRegistry: ${{ parameters.azureContainerRegistry }}
      dockerFile: ${{ parameters.imageDockerfilePath }}
      imageName: ${{ parameters.azureContainerRegistry }}/${{ parameters.imageName }}:$(Build.SourceVersion)

  - task: Docker@1
    displayName: Push image
    inputs:
      command: push
      azureSubscriptionEndpoint: azurerm-nonprod
      azureContainerRegistry: hmcts.azurecr.io
      imageName: ${{ parameters.azureContainerRegistry }}/${{parameters.imageName}}:$(Build.SourceVersion)
