name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build - Node 12 Alpine
        id: docker_build_node12_alpine
        uses: docker/build-push-action@v2
        with:
          context: ./12/alpine
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}/base/node:12-alpine
      - name: Build - Node 12 Buster Slim
        id: docker_build_node12_busterslim
        uses: docker/build-push-action@v2
        with:
          context: ./12/buster-slim
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}/base/node:12-buster-slim
      - name: Build - Node 14 Alpine
        id: docker_build_node14_alpine
        uses: docker/build-push-action@v2
        with:
          context: ./14/alpine
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}/base/node:14-alpine
      - name: Build - Node 14 Buster Slim
        id: docker_build_node14_busterslim
        uses: docker/build-push-action@v2
        with:
          context: ./14/buster-slim
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.AZURE_CONTAINER_REGISTRY_URL }}/base/node:14-buster-slim
